In [5]:
import pandas as pd
import numpy as np

iris = pd.read_csv("./iris.csv")
df = pd.DataFrame(iris)
df.columns=[0,1,2,3,4]

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2 = df.copy()
df2[4] = le.fit_transform(df2[4])

onehot_df = pd.get_dummies(df2,columns=[4])



y = np.array(onehot_df[["4_0","4_1","4_2"]], dtype=np.float32)
type(y)
print(y[0])
print(y[50])
print(y[100])

[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


In [6]:
X = df[[0,1,2,3]]
y = df[4]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: 4, Length: 149, dtype: object

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0, stratify=y)


from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

print(X_train_std)

[[ 1.20866551e+00  1.08123298e-01  7.36923959e-01  1.43944154e+00]
 [ 2.59081276e-01 -1.08123298e-01  6.23968776e-01  7.75280406e-01]
 [ 6.15175364e-01  3.24369893e-01  8.49879142e-01  1.43944154e+00]
 [-9.27899018e-01  5.40616488e-01 -1.18331415e+00 -9.51538554e-01]
 [-1.40269114e+00  3.24369893e-01 -1.23979175e+00 -1.35003524e+00]
 [-9.27899018e-01  7.56863083e-01 -1.29626934e+00 -1.35003524e+00]
 [-5.71804930e-01 -1.08123298e-01  3.98058410e-01  3.76783723e-01]
 [ 6.15175364e-01 -7.56863083e-01  8.49879142e-01  9.08112634e-01]
 [ 3.77779305e-01 -3.24369893e-01  2.85103227e-01  1.11119267e-01]
 [ 1.08996748e+00 -1.08123298e-01  9.62834325e-01  1.17377709e+00]
 [-9.27899018e-01  1.62184946e+00 -1.23979175e+00 -1.35003524e+00]
 [ 2.59081276e-01 -1.08123298e-01  4.54536001e-01  2.43951495e-01]
 [ 9.71269452e-01 -1.08123298e-01  6.80446368e-01  6.42448178e-01]
 [ 4.96477335e-01 -1.18935627e+00  6.23968776e-01  3.76783723e-01]
 [ 1.20866551e+00  1.08123298e-01  6.23968776e-01  3.76783723e

In [11]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
pca.explained_variance_ratio_

array([0.72641723, 0.2327667 ])

In [12]:
X_train_pca

array([[ 1.8448511 ,  0.65658815],
       [ 0.96566562,  0.05310802],
       [ 1.54467214,  0.6274865 ],
       [-1.85316675,  0.06486721],
       [-2.30187345, -0.33971304],
       [-2.20166809,  0.24130152],
       [ 0.17600084, -0.29418661],
       [ 1.52878118, -0.39417891],
       [ 0.511018  , -0.1403501 ],
       [ 1.82106489,  0.40270311],
       [-2.39688391,  1.03822763],
       [ 0.56606911,  0.02271174],
       [ 1.29395537,  0.32393715],
       [ 1.14858042, -0.86968257],
       [ 1.17712704,  0.60039653],
       [-2.38188124, -1.07705306],
       [ 2.81027141,  0.42650451],
       [-0.44261831, -1.918556  ],
       [ 0.56248049, -0.38749875],
       [ 1.4099832 ,  0.24428627],
       [ 1.98503377,  0.86243351],
       [-0.56141761, -1.76568125],
       [-2.08520444,  1.39000226],
       [-2.61428361,  1.67324212],
       [ 0.17122773, -0.73385222],
       [ 0.85673385,  0.04737746],
       [-2.4681793 ,  0.01654161],
       [ 0.6036928 , -0.21671528],
       [ 1.2911839 ,