In [18]:
import pandas as pd
import numpy as np

iris = pd.read_csv("./iris.csv")
df = pd.DataFrame(iris)
df.columns=[0,1,2,3,4]

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2 = df.copy()
df2[4] = le.fit_transform(df2[4])

onehot_df = pd.get_dummies(df2,columns=[4])



y = np.array(onehot_df[["4_0","4_1","4_2"]], dtype=np.float32)
type(y)
print(y[0])
print(y[50])
print(y[100])

[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


In [23]:
X = df[[0,1,2,3]]
y = df[4]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: 4, Length: 149, dtype: object

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0, stratify=y)


from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

print(X_train_std)

[[ 1.20866551e+00  1.08123298e-01  7.36923959e-01  1.43944154e+00]
 [ 2.59081276e-01 -1.08123298e-01  6.23968776e-01  7.75280406e-01]
 [ 6.15175364e-01  3.24369893e-01  8.49879142e-01  1.43944154e+00]
 [-9.27899018e-01  5.40616488e-01 -1.18331415e+00 -9.51538554e-01]
 [-1.40269114e+00  3.24369893e-01 -1.23979175e+00 -1.35003524e+00]
 [-9.27899018e-01  7.56863083e-01 -1.29626934e+00 -1.35003524e+00]
 [-5.71804930e-01 -1.08123298e-01  3.98058410e-01  3.76783723e-01]
 [ 6.15175364e-01 -7.56863083e-01  8.49879142e-01  9.08112634e-01]
 [ 3.77779305e-01 -3.24369893e-01  2.85103227e-01  1.11119267e-01]
 [ 1.08996748e+00 -1.08123298e-01  9.62834325e-01  1.17377709e+00]
 [-9.27899018e-01  1.62184946e+00 -1.23979175e+00 -1.35003524e+00]
 [ 2.59081276e-01 -1.08123298e-01  4.54536001e-01  2.43951495e-01]
 [ 9.71269452e-01 -1.08123298e-01  6.80446368e-01  6.42448178e-01]
 [ 4.96477335e-01 -1.18935627e+00  6.23968776e-01  3.76783723e-01]
 [ 1.20866551e+00  1.08123298e-01  6.23968776e-01  3.76783723e

In [40]:
from sklearn.decomposition import PCA

pca = PCA()
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
pca.explained_variance_ratio_

array([0.72641723, 0.2327667 , 0.03557513, 0.00524093])

In [41]:
X_train_pca

array([[ 1.84485110e+00,  6.56588154e-01,  1.94530294e-01,
         4.63881713e-01],
       [ 9.65665624e-01,  5.31080178e-02,  3.65236270e-01,
        -2.19637379e-02],
       [ 1.54467214e+00,  6.27486503e-01,  6.83156408e-01,
         1.77451568e-01],
       [-1.85316675e+00,  6.48672053e-02,  3.88927618e-02,
         1.37743883e-01],
       [-2.30187345e+00, -3.39713044e-01,  5.31417735e-02,
        -1.24846202e-01],
       [-2.20166809e+00,  2.41301524e-01, -1.76571074e-01,
        -1.23149166e-03],
       [ 1.76000836e-01, -2.94186609e-01,  6.67024892e-01,
        -2.76809926e-01],
       [ 1.52878118e+00, -3.94178913e-01,  5.81905882e-02,
         4.80678858e-02],
       [ 5.11017996e-01, -1.40350099e-01, -2.45218744e-01,
        -2.43843636e-02],
       [ 1.82106489e+00,  4.02703108e-01,  7.68236766e-02,
         1.42032897e-01],
       [-2.39688391e+00,  1.03822763e+00,  5.46529902e-02,
        -1.58477039e-01],
       [ 5.66069114e-01,  2.27117426e-02,  8.76466922e-04,
      